import type { SkillRecord } from "./models";

export const BUILTIN_SKILLS: SkillRecord[] = [
  {
    id: "git-workflow",
    name: "Git & Release Hygiene",
    description: "Conventional commits, branch discipline, atomic modifications, and clean pull request preparation.",
    content: [
      "# Git & Release Hygiene",
      "",
      "When working with Git and version control:",
      "- Make focused, atomic commits that address one concern at a time.",
      "- Use Conventional Commits formatting: `feat:`, `fix:`, `refactor:`, `test:`, `docs:`, `chore:`.",
      "- Never commit secrets, `.env` files, API keys, or machine-local credentials.",
      "- Check `git status` and `git diff` before and after file changes to verify clean modifications.",
      "- Maintain clean working tree discipline and avoid unintended modifications in unrelated files.",
    ].join("\n"),
    enabled: true,
    level: "global",
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: "tdd-testing",
    name: "Test-Driven & Quality Assurance",
    description: "Methodical test authoring, test execution, coverage preservation, and regression avoidance.",
    content: [
      "# Test-Driven & Quality Assurance",
      "",
      "When implementing or updating features:",
      "- Follow the Red-Green-Refactor cycle where appropriate: write/update tests to demonstrate requirements, implement, verify pass.",
      "- Use project test runners (e.g. `vitest run`, `npm test`, `pytest`, `cargo test`) via `run_command`.",
      "- Test edge cases: empty collections, null/undefined inputs, boundary conditions, timeouts, and network/storage errors.",
      "- When fixing a bug, add a regression test that fails before the fix and passes after.",
      "- Keep tests deterministic and isolated: avoid shared mutable state between test cases.",
    ].join("\n"),
    enabled: true,
    level: "global",
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: "code-refactoring",
    name: "Clean Code & Refactoring",
    description: "SOLID design principles, reducing cyclomatic complexity, DRY patterns, and safe modular refactoring.",
    content: [
      "# Clean Code & Refactoring",
      "",
      "When designing or refactoring code:",
      "- Follow Single Responsibility, Open/Closed, and Dependency Inversion principles.",
      "- Keep functions small, focused, and pure where practical.",
      "- Eliminate code duplication (DRY) by abstracting reusable utilities.",
      "- Replace complex conditionals with polymorphism, lookup tables, or guard clauses.",
      "- Preserve backward compatibility for public APIs and configuration schemas.",
      "- Favor explicit typing, immutable data structures, and predictable error handling over implicit assumptions.",
    ].join("\n"),
    enabled: true,
    level: "global",
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: "debug-diagnostics",
    name: "Root-Cause Debugging & Diagnostics",
    description: "Systematic failure analysis, reproduction, error stack trace inspection, and surgical fixing.",
    content: [
      "# Root-Cause Debugging & Diagnostics",
      "",
      "When troubleshooting defects or test failures:",
      "- Reproduce the problem reliably before attempting fixes.",
      "- Read full stack traces, log lines, and error outputs to pinpoint the exact failure point.",
      "- Formulate specific hypotheses and test them systematically (e.g. inspecting intermediate state).",
      "- Avoid 'shotgun debugging' or speculative edits. Understand why the failure happens.",
      "- Fix the root cause at the source rather than masking symptoms with ad-hoc null checks.",
      "- Re-run test suites after fixing to confirm resolution and prevent collateral regressions.",
    ].join("\n"),
    enabled: true,
    level: "global",
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: "performance-optimization",
    name: "Performance & Resource Optimization",
    description: "Asynchronous concurrency, memoization, I/O efficiency, and memory leak prevention.",
    content: [
      "# Performance & Resource Optimization",
      "",
      "When writing performance-sensitive code:",
      "- Avoid unnecessary re-computations; leverage memoization, caching, and indexed data lookups.",
      "- Use parallel asynchronous operations (`Promise.all`) when tasks are independent.",
      "- Stream or batch large file reads, network payloads, and database queries rather than buffering everything into memory.",
      "- Clean up event listeners, timers, subscriptions, and child processes to avoid memory and resource leaks.",
      "- Keep bundle size lean by avoiding unnecessary heavy external dependencies.",
    ].join("\n"),
    enabled: true,
    level: "global",
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: "security-hardening",
    name: "Security & Defensive Engineering",
    description: "Input sanitization, injection defense, secret protection, and OWASP compliance.",
    content: [
      "# Security & Defensive Engineering",
      "",
      "When writing secure systems:",
      "- Validate and sanitize all external inputs, parameters, file paths, and environment values.",
      "- Never execute untrusted string interpolation directly in shell commands or SQL queries.",
      "- Prevent path traversal by validating and anchoring file paths against the project root.",
      "- Never log or render sensitive credentials (API keys, authorization headers, passwords).",
      "- Adhere to the principle of least privilege in tool invocations and system interactions.",
    ].join("\n"),
    enabled: true,
    level: "global",
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: "api-design",
    name: "API & Protocol Design",
    description: "Typed schemas, REST/JSON-RPC protocols, error handling contracts, and idempotent operations.",
    content: [
      "# API & Protocol Design",
      "",
      "When designing APIs and interfaces:",
      "- Define clear, strongly-typed contracts (TypeScript interfaces, JSON-RPC methods, Zod schemas).",
      "- Design idempotent mutation methods with clear preconditions and postconditions.",
      "- Return structured, actionable error objects with consistent error codes and descriptive messages.",
      "- Document all parameters, return types, and failure modes explicitly.",
      "- Maintain API versioning and backward compatibility across upgrades.",
    ].join("\n"),
    enabled: true,
    level: "global",
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: "ui-ux-craft",
    name: "UI/UX & Frontend Craftsmanship",
    description: "Modern React patterns, accessibility (WCAG/ARIA), responsive design, and fluid interactions.",
    content: [
      "# UI/UX & Frontend Craftsmanship",
      "",
      "When building user interfaces:",
      "- Build accessible components with semantic HTML, ARIA roles, and full keyboard navigability.",
      "- Maintain visual hierarchy, consistent typography, spacing scales, and responsive design.",
      "- Handle loading, empty, and error states gracefully with informative feedback.",
      "- Ensure seamless dark/light theme support with appropriate contrast ratios.",
      "- Keep UI responsive and smooth by avoiding heavy synchronous work on the main thread.",
    ].join("\n"),
    enabled: true,
    level: "global",
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: "documentation",
    name: "Technical Documentation & ADRs",
    description: "Clear technical specifications, README guides, Architecture Decision Records, and inline docs.",
    content: [
      "# Technical Documentation & ADRs",
      "",
      "When authoring technical documentation:",
      "- Provide concise, high-signal explanations with working code examples.",
      "- Document architectural decisions using ADR format: Context, Decision, Consequences.",
      "- Keep READMEs clear with quickstart guides, architecture diagrams, and configuration references.",
      "- Add meaningful JSDoc/TSDoc comments for exported functions, types, and modules.",
    ].join("\n"),
    enabled: true,
    level: "global",
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: "code-review",
    name: "Code Review & Verification Checklist",
    description: "Comprehensive PR review rubric, static analysis, boundary checks, and quality inspection.",
    content: [
      "# Code Review & Verification Checklist",
      "",
      "When reviewing pull requests and changes:",
      "- Verify requirements completeness and edge-case handling.",
      "- Check for unintended side effects, performance regressions, and memory leaks.",
      "- Inspect type safety, error boundaries, and null/undefined handling.",
      "- Ensure test coverage exists and all test suites pass.",
      "- Verify adherence to project formatting and linting rules.",
    ].join("\n"),
    enabled: true,
    level: "global",
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
];
