import type { SkillRecord } from "./models";

/**
 * The bundled skill library.
 *
 * These are loaded through **progressive disclosure**: only `name` +
 * `description` reach the model on every turn (a few dozen tokens each); the
 * `content` body is fetched with the `use_skill` tool the moment a skill
 * matches the task. That means the library can be large — an inactive skill
 * costs almost nothing.
 *
 * Authoring rules (they are what makes a skill actually fire correctly):
 *  - `description` is written in the third person and says BOTH what the skill
 *    does AND when to use it. Vague descriptions never get activated.
 *  - `content` is imperative, concrete and short. Under ~500 lines.
 *  - `triggers` adds literal phrases that should activate the skill.
 */
export const BUILTIN_SKILLS: SkillRecord[] = [
  {
    id: "task-decomposition",
    name: "Task Decomposition & Execution",
    description:
      "Break a large or ambiguous request into an ordered, verifiable plan and execute it step by step with a live todo list. Use for any multi-step feature work, migration, or vague request.",
    triggers: ["break this down", "plan this out", "large task", "multi-step", "where do I start"],
    allowedTools: ["todo_write", "read_file", "glob", "grep", "code_intel", "Task", "verify"],
    content: [
      "# Task Decomposition & Execution",
      "",
      "For any task with more than two or three moving parts:",
      "",
      "1. **Restate the goal.** One sentence: what is true when this is done? If you cannot state it, ask.",
      "2. **Explore before planning.** Find the code that will actually change (grep/glob/code_intel). Read the conventions already there. Never plan against an imagined codebase.",
      "3. **Write the plan as a todo list** (`todo_write`) with imperative, verifiable items — `Add retry to the HTTP client`, not `Handle errors`. Each item must be finishable and checkable.",
      "4. **Order by dependency and risk.** Spikes and unknowns first, irreversible steps last. Put the risky core before the polish.",
      "5. **One item in progress at a time.** Mark it `in_progress`, do it, mark it `completed` immediately. Never batch completions at the end.",
      "6. **Re-plan when reality disagrees.** A wrong plan is cheap to fix early and expensive to defend. Update the list out loud.",
      "7. **Verify at the end** with the project's real checks (`verify`) and report per item.",
      "",
      "Anti-patterns: writing code before step 2; a todo list that is really one giant item; marking things complete that were only attempted; reporting success without a verification run.",
    ].join("\n"),
    enabled: true,
    level: "global",
    source: "builtin",
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: "verification-loop",
    name: "Verification & Evidence-Based Completion",
    description:
      "Never report done without running the project's real checks. Use after any code change, before claiming success, and when reporting test or build status.",
    triggers: ["is it done", "verify", "run the tests", "make sure it works", "did that work"],
    allowedTools: ["verify", "run_command", "read_file", "grep"],
    content: [
      "# Verification & Evidence-Based Completion",
      "",
      "A change is done when it is *demonstrated*, not when it looks right.",
      "",
      "## The loop",
      "1. Make the change.",
      "2. Run the project's checks (`verify`, or the explicit command). Typecheck → lint → tests → build, in that order: cheap checks first.",
      "3. Read the output. Failures are information: fix the cause, not the symptom. Re-run.",
      "4. Prove the specific behaviour changed — the test you added must fail before the fix and pass after.",
      "5. Only then report completion, quoting the command and its result.",
      "",
      "## Rules",
      "- Never say \"should work\", \"likely passes\", or \"I believe\". Run it.",
      "- If a check cannot run (missing tool, network, credentials), say so explicitly and say what is unverified. Partial verification reported honestly beats confident guessing.",
      "- Do not weaken a test, add a broad skip, or loosen a type to make a check pass. Fix the code, or explain why the check is wrong.",
      "- Regression-test every bug fix: the test is the deliverable as much as the patch is.",
      "- After a verification failure, do not retry the same change unchanged. Change the hypothesis first.",
      "",
      "## Reporting",
      "Report: what changed (files), which commands you ran, their exit status, and anything left unverified.",
    ].join("\n"),
    enabled: true,
    level: "global",
    source: "builtin",
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: "systematic-debugging",
    name: "Systematic Debugging",
    description:
      "Hypothesis-driven root-cause debugging: reproduce, isolate, bisect, fix the cause, add a regression test. Use for bugs, failing tests, stack traces, and 'it works on my machine'.",
    triggers: ["bug", "fails", "error", "exception", "stack trace", "not working", "regression", "flaky"],
    allowedTools: ["read_file", "grep", "code_intel", "run_command", "verify", "git"],
    content: [
      "# Systematic Debugging",
      "",
      "Debugging is search, and search needs a hypothesis. Shotgun edits cost more than they find.",
      "",
      "## Process",
      "1. **Read the error precisely.** Quote it. Note the exact file, line, and the input that produced it.",
      "2. **Reproduce deterministically.** A minimal command or test that fails every time. If you cannot reproduce it, you cannot verify a fix — say so instead of guessing.",
      "3. **Locate the boundary.** Where does observed behaviour first diverge from expected? Binary-search the path: log/inspect at the midpoint, decide which half to keep.",
      "4. **Form 2-3 hypotheses** and rank them by how cheaply they can be falsified. Test the cheapest discriminator first.",
      "5. **Confirm the mechanism.** You must be able to say *why* the failure happens, in one sentence, before you fix it.",
      "6. **Fix the cause,** at the layer that owns it. A null check at the call site is a symptom fix; the real fix is wherever the invariant is broken.",
      "7. **Add a regression test** that fails before and passes after.",
      "8. **Check for siblings:** the same mistake usually appears 2-3 times. Grep for the pattern.",
      "",
      "## Tools",
      "- `git bisect` when you know it used to work.",
      "- Binary-search by disabling halves of the input or config.",
      "- Print the *values*, not just the control flow — most \"impossible\" states are a wrong assumption about data.",
      "",
      "## Anti-patterns",
      "Changing several things at once; adding defensive code without understanding the failure; fixing the test instead of the code; declaring it flaky to move on.",
    ].join("\n"),
    enabled: true,
    level: "global",
    source: "builtin",
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: "multi-agent-orchestration",
    name: "Multi-Agent Orchestration",
    description:
      "How to delegate to specialist subagents: what to hand off, how to write a self-contained brief, when to parallelise, and how to verify the work that comes back. Use for large tasks, parallel exploration, or when context is getting long.",
    triggers: ["parallel", "delegate", "subagent", "many files", "research this", "spread across"],
    allowedTools: ["Task", "batch_tasks", "read_file", "grep", "verify"],
    content: [
      "# Multi-Agent Orchestration",
      "",
      "Subagents buy you two things: **context isolation** (their exploration never enters your window) and **concurrency**. They cost you a handoff, so delegate work where the brief is cheaper than the context.",
      "",
      "## Delegate when",
      "- Broad exploration: \"find every place we assume a single tenant\". The subagent reads 40 files; you get one page.",
      "- Independent workstreams that touch different files (run them in one `batch_tasks` call).",
      "- Verification by a fresh pair of eyes (reviewer) after you implement.",
      "- Work you would otherwise re-do after compaction.",
      "",
      "## Do not delegate when",
      "- The task needs the reasoning you just did — re-establishing it costs more than doing it.",
      "- Two tasks would edit the same file (they will conflict; sequence them instead).",
      "- The task is one or two tool calls.",
      "",
      "## Writing a brief",
      "A subagent sees only what you send. Include: goal, exact files/paths, constraints and conventions, what NOT to touch, the acceptance criteria, and the report format you need back.",
      "",
      "## Verify what comes back",
      "A subagent report is a claim, not evidence. Spot-check the files it says it changed and run the checks. Ask for file:line references in the report so verification is cheap.",
      "",
      "## Patterns",
      "- **Fan-out / fan-in:** `batch_tasks` with N independent explorers → synthesise → implement.",
      "- **Pipeline:** `batch_tasks` with `depends_on` — explore → implement → test → review in one call.",
      "- **Adversarial:** one agent implements, another reviews the diff with fresh context.",
    ].join("\n"),
    enabled: true,
    level: "global",
    source: "builtin",
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: "context-economy",
    name: "Context Economy",
    description:
      "Techniques for getting the information you need without flooding the context window: targeted search, progressive reading, and summarising instead of dumping. Use when the transcript is long or files are large.",
    triggers: ["large file", "too much output", "find where", "search the repo"],
    allowedTools: ["grep", "glob", "code_intel", "read_file", "Task"],
    content: [
      "# Context Economy",
      "",
      "Every token you read is a token you cannot think with. Read deliberately.",
      "",
      "## Progressive reading",
      "1. `glob` / `list_dir` → shape of the tree.",
      "2. `grep` / `code_intel` → locate the symbol or concept.",
      "3. `read_file` with `start_line`/`end_line` → read only the region that matters.",
      "Full-file reads are a last resort, not a first move.",
      "",
      "## Searching",
      "- Search for the *concept* (\"where is the token refreshed\"), then the literal string.",
      "- One precise regex beats three broad greps; include a glob filter (`**/*.ts`) to cut the noise.",
      "- Cap results (`max_results`) — you need the 20 relevant hits, not 2000.",
      "",
      "## Keeping the window small",
      "- Delegate exploration-heavy work to a subagent and take back only its report.",
      "- Persist durable findings to `memory` instead of re-deriving them next turn.",
      "- Do not paste large outputs into your own reasoning; quote the 3 lines that matter.",
      "- When the transcript is compacted, re-read the files you still need rather than trusting recall.",
    ].join("\n"),
    enabled: true,
    level: "global",
    source: "builtin",
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: "codebase-onboarding",
    name: "Codebase Onboarding",
    description:
      "Map an unfamiliar repository quickly: entry points, architecture, conventions, build and test commands, and where the tests live. Use at the start of work in a new project.",
    triggers: ["new project", "unfamiliar", "how does this work", "onboard", "understand the codebase"],
    allowedTools: ["read_file", "glob", "grep", "code_intel", "run_command", "memory"],
    content: [
      "# Codebase Onboarding",
      "",
      "Goal: a one-paragraph mental model plus the commands to change things safely.",
      "",
      "1. **Manifest & docs.** `package.json` / `pyproject.toml` / `Cargo.toml` / `go.mod` → name, scripts, dependencies. README and any `docs/`, `adr/`, `AGENTS.md`, `CONTRIBUTING.md`.",
      "2. **Tree shape.** `list_dir` on the root and one level into `src/`. Note the layering (app / domain / infra, or routes / services / db).",
      "3. **Entry points.** The main/cli/server file, and the router or command registry. `code_intel` for exported symbols.",
      "4. **Conventions.** Read 2-3 representative files end to end: naming, error handling, logging, test style, import ordering. Copy what is there.",
      "5. **Tests.** Where they live, how they are run (`verify`), what a good test looks like here.",
      "6. **State & boundaries.** Config, env vars, database or external clients, and where credentials come from.",
      "7. **Record it.** Write the durable parts (architecture, commands, gotchas) to `memory` so the next session starts at step 8.",
      "",
      "Report back: stack, entry points, layering, commands, and the 2-3 conventions a new change must respect.",
    ].join("\n"),
    enabled: true,
    level: "global",
    source: "builtin",
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: "refactoring-playbook",
    name: "Safe Refactoring Playbook",
    description:
      "Change the design without changing the behaviour: characterisation tests, small verified steps, strangler-pattern migrations, and knowing when to stop. Use for large refactors and migrations.",
    triggers: ["refactor", "clean up", "migrate", "rename across", "extract", "tech debt"],
    allowedTools: ["read_file", "grep", "patch_file", "verify", "run_command", "todo_write"],
    content: [
      "# Safe Refactoring Playbook",
      "",
      "Refactoring changes structure while behaviour stays identical. If behaviour changes, it is a rewrite and needs its own tests.",
      "",
      "## Sequence",
      "1. **Write characterisation tests first.** Pin the current behaviour (including the odd bits) so the refactor has a safety net. If you cannot test it, you cannot safely refactor it — say so.",
      "2. **Pick the smallest seam** that moves you toward the target design.",
      "3. **One atomic step at a time:** extract → rename → move → change signature. Verify (`verify`) after each. A green run after every step keeps the bisect window at one commit.",
      "4. **Prefer additive change.** Add the new path, switch callers one by one, then delete the old one (strangler pattern). Big-bang swaps fail.",
      "5. **Keep commits atomic** and independent so any one can be reverted.",
      "6. **Stop when the goal is met.** Polishing unrelated code in the same pass makes the diff unreviewable.",
      "",
      "## Rules",
      "- Never mix a refactor with a behaviour change or a feature.",
      "- Mechanical renames: use the editor/IDE-grade tool or a precise grep, then verify — never a blind find-and-replace across the repo.",
      "- If a step makes the code worse and you cannot finish it today, revert it rather than leaving it half-done.",
      "- Watch for the silent contract change: an exported type, a serialised shape, an env var, a CLI flag.",
    ].join("\n"),
    enabled: true,
    level: "global",
    source: "builtin",
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: "security-audit",
    name: "Security & Secret Hygiene",
    description:
      "Review code for injection, secret leakage, path traversal, unsafe deserialisation, auth gaps and risky dependencies. Use when touching auth, input handling, file paths, or anything user-supplied.",
    triggers: ["security", "vulnerable", "injection", "secret", "api key", "sanitize", "auth"],
    allowedTools: ["read_file", "grep", "glob", "run_command"],
    content: [
      "# Security & Secret Hygiene",
      "",
      "## Never commit or render",
      "API keys, tokens, passwords, connection strings, private keys. Check `git status`/`git diff` before and after. If a secret was written to a file, treat it as leaked and rotate it — deleting the commit is not enough.",
      "",
      "## Review checklist",
      "- **Injection:** is any untrusted value concatenated into SQL, a shell command, `eval`, a template, or a log/HTML sink? Use parameterised queries and argument arrays.",
      "- **Path traversal:** resolve user paths against an explicit root and reject anything that escapes it.",
      "- **Input validation:** validate at the boundary (types, length, allowed values), and again at the trust boundary.",
      "- **Auth & authorisation:** is the check on every path, including the helper and the background job? Deny by default.",
      "- **Deserialisation:** never deserialise untrusted input into executable types.",
      "- **Output:** do not log credentials, tokens, or full request bodies with secrets.",
      "- **Dependencies:** watch for unmaintained packages, known CVEs, and newly added packages with install scripts.",
      "",
      "## Reporting",
      "Classify each finding: **Critical / Warning / Suggestion**, with file:line, the concrete risk, and the specific fix. No vague \"consider validating input\".",
    ].join("\n"),
    enabled: true,
    level: "global",
    source: "builtin",
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: "memory-discipline",
    name: "Memory Discipline",
    description:
      "What belongs in durable memory and how to write it so a future session can act on it. Use when you learn a project convention, an architecture decision, a user preference, or a non-obvious gotcha.",
    triggers: ["remember", "from now on", "always", "prefer", "convention", "decision"],
    allowedTools: ["memory"],
    content: [
      "# Memory Discipline",
      "",
      "Memory is a curated notebook, not a transcript dump. Write it when the knowledge cost real work to obtain.",
      "",
      "## Write when you learn",
      "- A **decision** and *why* (\"chose Redis over Memcached for TTL semantics\").",
      "- A **convention** that is not obvious from the code (\"all migrations must be additive\").",
      "- A **gotcha**: the setup step that is not in the README, the test that needs a running service.",
      "- A **user preference**: formatting, commit style, review expectations.",
      "- A **root cause** that took more than a few minutes to find.",
      "",
      "## Do not write",
      "Anything derivable by reading the code (it will rot), transient task state, secrets/credentials, or anything longer than a short page.",
      "",
      "## How to write it",
      "- One topic per note, keyed by a kebab-case slug: `auth-flow`, `release-process`, `test-setup`.",
      "- Lead with the conclusion; add the reasoning in a line or two.",
      "- Include the evidence: file paths, commands, versions.",
      "- Update or replace a note when it goes stale; do not append a contradictory note.",
      "",
      "## Recall",
      "Search memory at the start of non-trivial work and before claiming something is impossible — the answer may already be stored.",
    ].join("\n"),
    enabled: true,
    level: "global",
    source: "builtin",
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: "git-workflow",
    name: "Git & Release Hygiene",
    description:
      "Conventional commits, branch discipline, atomic changes, and clean pull-request preparation. Use before committing, branching, or opening a PR.",
    triggers: ["commit", "branch", "pull request", "pr", "git"],
    allowedTools: ["run_command", "read_file", "grep"],
    content: [
      "# Git & Release Hygiene",
      "",
      "When working with Git and version control:",
      "- Make focused, atomic commits that address one concern at a time.",
      "- Use Conventional Commits formatting: `feat:`, `fix:`, `refactor:`, `test:`, `docs:`, `chore:`.",
      "- Never commit secrets, `.env` files, API keys, or machine-local credentials.",
      "- Check `git status` and `git diff` before and after file changes to verify clean modifications.",
      "- Review your own diff before committing: would you approve this? Remove debug code and unrelated edits.",
      "- Write PR descriptions that say what changed, why, and how it was verified (commands + results).",
      "- Maintain clean working tree discipline and avoid unintended modifications in unrelated files.",
    ].join("\n"),
    enabled: true,
    level: "global",
    source: "builtin",
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: "tdd-testing",
    name: "Test-Driven & Quality Assurance",
    description:
      "Test-first workflow, edge-case coverage, deterministic tests, and regression discipline. Use when adding behaviour, fixing bugs, or reviewing coverage.",
    triggers: ["test", "tdd", "coverage", "unit test", "integration test", "regression"],
    allowedTools: ["read_file", "write_file", "patch_file", "run_command", "verify"],
    content: [
      "# Test-Driven & Quality Assurance",
      "",
      "When implementing or updating features:",
      "- Follow Red-Green-Refactor: write the failing test that expresses the requirement, implement, verify it passes, then clean up.",
      "- Use the project's own runner (`verify`, or `run_command` with the project's test command).",
      "- Test behaviour through the public interface, not private internals — tests that mirror the implementation break on every refactor.",
      "- Cover edge cases: empty collections, null/undefined, boundaries, timeouts, concurrent access, and error paths.",
      "- Every bug fix ships with a regression test that fails before the fix and passes after.",
      "- Keep tests deterministic and isolated: no shared mutable state, no real network, no dependence on wall-clock time or execution order.",
      "- One logical assertion per test. A test named `handlesEverything` verifies nothing.",
      "- Name tests after the behaviour: `rejects an expired token`, not `test_auth_3`.",
    ].join("\n"),
    enabled: true,
    level: "global",
    source: "builtin",
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: "code-refactoring",
    name: "Clean Code & Design",
    description:
      "SOLID design, small pure functions, DRY without over-abstraction, explicit error handling, and readable naming. Use when writing or reviewing code structure.",
    triggers: ["clean code", "design", "solid", "duplicate", "abstraction", "naming"],
    allowedTools: ["read_file", "patch_file", "code_intel", "grep"],
    content: [
      "# Clean Code & Design",
      "",
      "When designing or refactoring code:",
      "- Follow Single Responsibility, Open/Closed, and Dependency Inversion principles.",
      "- Keep functions small, focused, and pure where practical.",
      "- Eliminate duplication that carries a rule; leave accidental similarity alone. Three similar lines beat a premature abstraction.",
      "- Replace complex conditionals with polymorphism, lookup tables, or guard clauses.",
      "- Preserve backward compatibility for public APIs and configuration schemas.",
      "- Favor explicit typing, immutable data structures, and predictable error handling over implicit assumptions.",
      "- Name things after what they are for. If a name needs a comment, the name is wrong.",
      "- Delete dead code instead of commenting it out; version control is the archive.",
    ].join("\n"),
    enabled: true,
    level: "global",
    source: "builtin",
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: "debug-diagnostics",
    name: "Diagnostics & Observability",
    description:
      "Reading stack traces, logs and exit codes; adding the right instrumentation; diagnosing build, environment and dependency failures. Use for toolchain and environment problems.",
    triggers: ["build fails", "dependency", "install", "exit code", "logs", "env", "cannot find module"],
    allowedTools: ["run_command", "read_file", "grep", "web_fetch"],
    content: [
      "# Diagnostics & Observability",
      "",
      "When troubleshooting defects, build or environment failures:",
      "- Reproduce the problem reliably before attempting fixes; capture the exact command and exit code.",
      "- Read the whole error, not the last line. Most build failures name the real cause above the stack trace.",
      "- Check the environment first: versions (`node -v`, `python -V`), lockfile vs installed tree, PATH, and env vars.",
      "- Formulate specific hypotheses and test them one at a time; inspect intermediate state rather than guessing.",
      "- Avoid 'shotgun debugging' or speculative edits. Understand why the failure happens.",
      "- Fix the root cause at the source rather than masking symptoms with ad-hoc null checks or broad try/catch.",
      "- Re-run the full check suite after fixing to confirm resolution and catch collateral regressions.",
      "- When adding logging, log the decision (what was chosen) and the identifier, not the whole object — and never secrets.",
    ].join("\n"),
    enabled: true,
    level: "global",
    source: "builtin",
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: "performance-optimization",
    name: "Performance & Resource Optimization",
    description:
      "Measure before optimising: profiling, algorithmic complexity, concurrency, caching, and leak prevention. Use for slow paths, large data, and resource exhaustion.",
    triggers: ["slow", "performance", "memory leak", "optimise", "optimize", "latency", "n+1"],
    allowedTools: ["run_command", "read_file", "grep", "code_intel"],
    content: [
      "# Performance & Resource Optimization",
      "",
      "When writing performance-sensitive code:",
      "- Measure first. Name the hot path with a profile or a benchmark; optimise the top item, not the most interesting one.",
      "- Fix the algorithm before the constant factor: N+1 queries and accidental O(n²) beat any micro-optimisation.",
      "- Batch and stream: prefer one bulk query over N round-trips, and stream large files instead of buffering them.",
      "- Use parallel asynchronous operations (`Promise.all`) only when the tasks are genuinely independent.",
      "- Cache with an explicit invalidation rule and a bound. An unbounded cache is a leak.",
      "- Clean up event listeners, timers, subscriptions, and child processes to avoid resource leaks.",
      "- Keep bundle size lean: avoid heavy transitive dependencies for a small utility.",
      "- Record the measurement in your report — before/after numbers, and the workload they came from.",
    ].join("\n"),
    enabled: true,
    level: "global",
    source: "builtin",
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: "api-design",
    name: "API & Protocol Design",
    description:
      "Typed contracts, idempotency, structured errors, versioning and backward compatibility for REST/JSON-RPC/GraphQL interfaces. Use when designing or changing an interface.",
    triggers: ["api", "endpoint", "contract", "schema", "versioning", "json-rpc", "rest"],
    allowedTools: ["read_file", "patch_file", "code_intel", "glob"],
    content: [
      "# API & Protocol Design",
      "",
      "When designing APIs and interfaces:",
      "- Define clear, strongly-typed contracts (TypeScript interfaces, JSON-RPC methods, schema validators).",
      "- Design idempotent mutation methods with clear preconditions and postconditions.",
      "- Return structured, actionable error objects with stable codes and messages that say how to fix it.",
      "- Document all parameters, return types, and failure modes explicitly.",
      "- Maintain API versioning and backward compatibility across upgrades; additive changes first, removal in a major.",
      "- Validate at the boundary, then trust the types inside.",
      "- Keep the wire shape boring: consistent casing, ISO timestamps, null vs absent defined.",
    ].join("\n"),
    enabled: true,
    level: "global",
    source: "builtin",
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: "ui-ux-craft",
    name: "UI/UX & Frontend Craftsmanship",
    description:
      "Accessible, responsive, state-complete interfaces: semantic HTML, ARIA, keyboard navigation, loading/empty/error states, and theme support. Use for any user-facing component.",
    triggers: ["ui", "component", "frontend", "accessibility", "a11y", "responsive", "form"],
    allowedTools: ["read_file", "patch_file", "glob", "grep", "run_command"],
    content: [
      "# UI/UX & Frontend Craftsmanship",
      "",
      "When building user interfaces:",
      "- Build accessible components with semantic HTML, ARIA roles, and full keyboard navigability; every interactive control needs a focus state and an accessible name.",
      "- Maintain visual hierarchy, consistent typography, spacing scales, and responsive design.",
      "- Handle loading, empty, error, and permission-denied states explicitly — the states users actually see most.",
      "- Ensure seamless dark/light theme support with appropriate contrast ratios (WCAG AA).",
      "- Keep the UI responsive: no heavy synchronous work on the main thread; virtualise long lists.",
      "- Prefer the design system components already in the repo over a new one-off.",
      "- Test the behaviour a user would perform, not the implementation detail; assert on roles and labels.",
    ].join("\n"),
    enabled: true,
    level: "global",
    source: "builtin",
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: "documentation",
    name: "Technical Documentation & ADRs",
    description:
      "Write documentation that ships: quickstarts, ADRs (Context / Decision / Consequences), API references and precise doc comments. Use when documenting a system or decision.",
    triggers: ["documentation", "readme", "adr", "docs", "explain", "jsdoc"],
    allowedTools: ["read_file", "write_file", "patch_file", "glob"],
    content: [
      "# Technical Documentation & ADRs",
      "",
      "When authoring technical documentation:",
      "- Provide concise, high-signal explanations with working code examples that match the current API.",
      "- Document architectural decisions using ADR format: Context, Decision, Consequences (including what you gave up).",
      "- Keep READMEs clear with quickstart guides, architecture diagrams, and configuration references.",
      "- Add meaningful JSDoc/TSDoc comments for exported functions, types, and modules — say what it guarantees, not what the line does.",
      "- Write for the reader who is new: define the jargon once, then use it.",
      "- Prefer one canonical page over three that drift apart; delete docs that describe deleted behaviour.",
    ].join("\n"),
    enabled: true,
    level: "global",
    source: "builtin",
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: "code-review",
    name: "Code Review Checklist",
    description:
      "Rigorous review rubric: correctness, edge cases, security, performance, tests, and adherence to project conventions, with findings ranked by severity. Use when reviewing a diff or before declaring work complete.",
    triggers: ["review", "check my changes", "pr review", "audit", "diff"],
    allowedTools: ["read_file", "grep", "run_command", "verify", "memory"],
    content: [
      "# Code Review Checklist",
      "",
      "When reviewing pull requests and changes:",
      "- Verify requirements completeness and edge-case handling; trace the unhappy path.",
      "- Check for unintended side effects, performance regressions, and resource leaks.",
      "- Inspect type safety, error boundaries, and null/undefined handling.",
      "- Ensure test coverage exists for the new behaviour and that all suites pass (`verify`).",
      "- Verify adherence to project formatting, linting, and architectural conventions.",
      "- Confirm no secrets, debug code, or unrelated changes slipped into the diff.",
      "- Rank findings **Critical / Warning / Suggestion**, each with file:line and a concrete fix.",
      "- Distinguish blocking from optional, and say so — a review that blocks everything is ignored.",
    ].join("\n"),
    enabled: true,
    level: "global",
    source: "builtin",
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
];
